### ISSUE TITLE
About your project

### ISSUE THREAD

**Issue by 8Marchisio** [salimrabat/MasterThesisProject#1]
I am a student interested in searchable encryption and i want to learn more about your project.May i get your paper?Thanks a lot

**Comment by salimrabat** [comment]
Here's a link to the paper
https://kth.diva-portal.org/smash/record.jsf?pid=diva2%3A1638066&dswid=-7340
Will also add it in the README.md

**Comment by 8Marchisio** [comment]
I really appreciate.Thanks again！
